import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#006e2d",
        "surface-dim": "#131313",
        "on-error": "#690005",
        error: "#ffb4ab",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#ffdad9",
        "secondary-container": "#1c5329",
        outline: "#869585",
        "on-tertiary-container": "#730a1b",
        "primary-fixed": "#72fe8f",
        "on-tertiary": "#680114",
        "surface-container-highest": "#353534",
        "surface-tint": "#53e076",
        "secondary-fixed": "#b5f1b8",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#99d59d",
        "primary-fixed-dim": "#53e076",
        "on-surface": "#e5e2e1",
        surface: "#131313",
        secondary: "#99d59d",
        "on-error-container": "#ffdad6",
        "on-primary": "#003914",
        "outline-variant": "#3d4a3d",
        "surface-container-low": "#1c1b1b",
        primary: "#53e076",
        tertiary: "#ffb3b3",
        "surface-variant": "#353534",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#8cc690",
        "on-secondary": "#003914",
        "on-secondary-fixed": "#002108",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#881d28",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-primary-fixed": "#002108",
        "on-secondary-fixed-variant": "#195127",
        "primary-container": "#1db954",
        "on-surface-variant": "#bccbb9",
        "on-tertiary-fixed": "#400009",
        "on-primary-fixed-variant": "#005320",
        "surface-container": "#201f1f",
        background: "#131313",
        "on-primary-container": "#004118",
        "surface-container-high": "#2a2a2a",
        "tertiary-container": "#ff767b",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      transitionTimingFunction: {
        portfolio: "cubic-bezier(0.3, 0, 0.4, 1)",
      },
    },
  },
  plugins: [],
};
export default config;
